### ISSUE TITLE
Support for binary responses

### ISSUE THREAD

**Issue by curiousercreative** [erfanium/fastify-web-response#1]
Hi, thanks for writing this and the [associated work here](https://github.com/fastify/fastify/pull/4537). I first tried to use your plugin and found that it wasn't supporting binary responses (pdf file for example) but looking at your plugin I discovered the trick I've been searching for which is the `Readable.fromWeb` method. So all in all, I'm not using your plugin, but instead converting the ReadableStream (response body) which Fastify is happy to stream. Here's one of your examples modified for my solution:

```javascript
import { Readable } from 'node:stream'

app.route({
  method: "GET",
  url: "/",
  async handler() {
    const { body } = await fetch("https://example-api.com")
    return Readable.fromWeb(body)
  }
})
```

**Comment by erfanium** [comment]
@curiousercreative 
Thanks for reporting this.
Honestly, I don't have a time to check it myself to see what's wrong. I'll be happy if you create a PR for this.
